name: fpm-deployment

on: [push, pull, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            toolchain: {compiler: gcc, version: 13}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.1

      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: 3.x

      - name: Install requirements
        run: pip install --upgrade -r config/requirements.txt

      - uses: fortran-lang/setup-fortran@main
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Setup Fortran Package Manager
        uses: fortran-lang/setup-fpm@v5
        with:
          fpm-version: 'v0.10.0'

      - run: | # Just for deployment: create stdlib-fpm folder
          python config/fypp_deployment.py --deploy_stdlib_fpm

      - run: | # Just for deployment: create stdlib-fpm-xdp folder
          python config/fypp_deployment.py --deploy_stdlib_fpm --with_xdp

      - run: | # Just for deployment: create stdlib-fpm-qp folder
          python config/fypp_deployment.py --deploy_stdlib_fpm --with_qp

      - run: | # Just for deployment: create stdlib-fpm-xdp-qp folder
          python config/fypp_deployment.py --deploy_stdlib_fpm --with_xdp --with_qp

      - run: | # Just for deployment: create stdlib-fpm-ilp64 folder
          python config/fypp_deployment.py --deploy_stdlib_fpm --with_ilp64

      - run: | # Just for deployment: create stdlib-fpm-ilp64-xdp folder
          python config/fypp_deployment.py --deploy_stdlib_fpm --with_ilp64 --with_xdp

      - run: | # Just for deployment: create stdlib-fpm-ilp64-qp folder
          python config/fypp_deployment.py --deploy_stdlib_fpm --with_ilp64 --with_qp

      - run: | # Just for deployment: create stdlib-fpm-ilp64-xdp-qp folder
          python config/fypp_deployment.py --deploy_stdlib_fpm --with_ilp64 --with_xdp --with_qp

      - run: | # Use fpm gnu ci to check xdp and qp
          python config/fypp_deployment.py --with_xdp --with_qp
          fpm test --profile release --flag '-DWITH_XDP -DWITH_QP'

    # Update and deploy the f90 files generated by github-ci to the `stdlib-fpm` branch.
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: github.event_name != 'pull_request'
        with:
          BRANCH: stdlib-fpm
          FOLDER: stdlib-fpm

    # Update and deploy the f90 files generated by github-ci to the `stdlib-fpm-xdp` branch.
      - name: Deploy with xdp support 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: github.event_name != 'pull_request'
        with:
          BRANCH: stdlib-fpm-xdp
          FOLDER: stdlib-fpm-xdp

    # Update and deploy the f90 files generated by github-ci to the `stdlib-fpm-qp` branch.
      - name: Deploy with qp support 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: github.event_name != 'pull_request'
        with:
          BRANCH: stdlib-fpm-qp
          FOLDER: stdlib-fpm-qp

    # Update and deploy the f90 files generated by github-ci to the `stdlib-fpm-xdp-qp` branch.
      - name: Deploy with xdp and qp support 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: github.event_name != 'pull_request'
        with:
          BRANCH: stdlib-fpm-xdp-qp
          FOLDER: stdlib-fpm-xdp-qp

    # Update and deploy the f90 files generated by github-ci to the `stdlib-fpm-ilp64` branch.
      - name: Deploy with 64-bit integer support 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: github.event_name != 'pull_request'
        with:
          BRANCH: stdlib-fpm-ilp64
          FOLDER: stdlib-fpm-ilp64

    # Update and deploy the f90 files generated by github-ci to the `stdlib-fpm-ilp64-xdp` branch.
      - name: Deploy with 64-bit integer and xdp support 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: github.event_name != 'pull_request'
        with:
          BRANCH: stdlib-fpm-ilp64-xdp
          FOLDER: stdlib-fpm-ilp64-xdp

    # Update and deploy the f90 files generated by github-ci to the `stdlib-fpm-ilp64-qp` branch.
      - name: Deploy with 64-bit integer and qp support 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: github.event_name != 'pull_request'
        with:
          BRANCH: stdlib-fpm-ilp64-qp
          FOLDER: stdlib-fpm-ilp64-qp

    # Update and deploy the f90 files generated by github-ci to the `stdlib-fpm-ilp64-xdp-qp` branch.
      - name: Deploy with 64-bit integer, xdp, and qp support 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: github.event_name != 'pull_request'
        with:
          BRANCH: stdlib-fpm-ilp64-xdp-qp
          FOLDER: stdlib-fpm-ilp64-xdp-qp
