name: sync stdlib + enable XDP and QP

on:
  schedule:
    # --     m h d(m) m d(w)
    - cron: '0 *   *  * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: fetch upstream
        run: |
          git remote add upstream https://github.com/fortran-lang/stdlib.git
          git fetch upstream

          git checkout -B master upstream/master

      - name: commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git push --force origin master
